# Generated by Django 5.1.3 on 2024-11-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='Note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
