# Generated by Django 5.1.3 on 2024-11-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ride_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='Note',
            field=models.CharField(max_length=200),
        ),
    ]
