# Generated by Django 5.1.3 on 2024-11-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ride_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
